In [1]:
# importing
import pandas as pd

In [2]:
# creating data
pd.DataFrame({'yes':[11,20],'no':[33,78]})

   yes  no
0   11  33
1   20  78

In [3]:
# dataframe entries arenot limited to integers
pd.DataFrame({'Prekshya':[' Are you hungry?','Lets,Grab a food.'],'Sanjita':['yeah,sure.','Sure, why not?']})

            Prekshya         Sanjita
0    Are you hungry?      yeah,sure.
1  Lets,Grab a food.  Sure, why not?

In [4]:
# using index parameter
pd.DataFrame({'Prekshya':[' Are you hungry?','Lets,Grab a food.'],'Sanjita':['yeah,sure.','Sure, why not?']},index = ['Product A','Product B'])

                    Prekshya         Sanjita
Product A    Are you hungry?      yeah,sure.
Product B  Lets,Grab a food.  Sure, why not?

In [5]:
# series
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
pd.Series([11,22,33],index =['2011 sales','2022 sales','2033 sales'],name = 'Poduct A')

2011 sales    11
2022 sales    22
2033 sales    33
Name: Poduct A, dtype: int64

In [7]:
# Reading data files
population_analysis = pd.read_csv("C:/Users/Prekshya/Desktop/world-population-analysis/data/Dataset.csv")

In [8]:
population_analysis.shape

(260, 11)

In [10]:
population_analysis.head()

,Serial Number,Country Code,Country Name,Area,Land Area,Water Area,Population,Population Growth Rate,Birth Rate,Death Rate,Migration Rate
0,1,af,Afghanistan,652230.0,652230.0,0.0,32564342.0,2.32,38.57,13.89,1.51
1,2,al,Albania,28748.0,27398.0,1350.0,3029278.0,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741.0,2381741.0,0.0,39542166.0,1.84,23.67,4.31,0.92
3,4,an,Andorra,468.0,468.0,0.0,85580.0,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700.0,1246700.0,0.0,19625353.0,2.78,38.78,11.49,0.46

In [9]:
import pandas as pd
pd.Series([30,35,40], index = ['2015 sales','2020 sales','2025 sales'], name = 'Product A')

2015 sales    30
2020 sales    35
2025 sales    40
Name: Product A, dtype: int64