In [1]:
# importing
import pandas as pd

In [2]:
# creating data
pd.DataFrame({'yes':[11,20],'no':[33,78]})

   yes  no
0   11  33
1   20  78

In [6]:
# dataframe entries arenot limited to integers
pd.DataFrame({'Prekshya':[' Are you hungry?','Lets,Grab a food.'],'Sanjita':['yeah,sure.','Sure, why not?']})

            Prekshya         Sanjita
0    Are you hungry?      yeah,sure.
1  Lets,Grab a food.  Sure, why not?

In [9]:
# using index parameter
pd.DataFrame({'Prekshya':[' Are you hungry?','Lets,Grab a food.'],'Sanjita':['yeah,sure.','Sure, why not?']},index = ['Product A','Product B'])

                    Prekshya         Sanjita
Product A    Are you hungry?      yeah,sure.
Product B  Lets,Grab a food.  Sure, why not?

In [12]:
# series
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
pd.Series([11,22,33],index =['2011 sales','2022 sales','2033 sales'],name = 'Poduct A')

2011 sales    11
2022 sales    22
2033 sales    33
Name: Poduct A, dtype: int64

In [18]:
# Reading data files
population_analysis = pd.read_csv("C:/Users/Prekshya/Desktop/world-population-analysis/data/Dataset.csv")